owner: hexaaagon
repo: status

sites:
  - name: "Web - Main Website"
    url: https://main-web-ezl.pages.dev/
    maxResponseTime: 7500
  - name: "Web - CDN Website"
    url: https://cdnsites.hexaa11222474.workers.dev/
    maxResponseTime: 7500

status-website:
  name: "Hexagonn Project Status"
  theme: "night"
  cname: status.hexagonn.my.id
  introTitle: "Welcome to **Hexagonn Project Status!**"
  introMessage: "This is **Hexagonn Project Status** for viewing my Project either is online or not!"
  css: 'nav{animation:1s ease-in-out fadeInDown}main{animation:1s ease-in-out fadeIn}'
  links:
    - rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/hexaaagon
